echo testcase1
./a.out testdata/testcase1.txt
echo testcase2
./a.out testdata/testcase2.txt
echo testcase3
./a.out testdata/testcase3.txt
echo testcase4
./a.out testdata/testcase4.txt
echo testcase5
./a.out testdata/testcase5.txt
echo testcase6
./a.out testdata/testcase6.txt
echo testcase7
./a.out testdata/testcase7.txt
echo testcase8
./a.out testdata/testcase8.txt
echo testcase9
./a.out testdata/testcase9.txt
echo testcase10
./a.out testdata/testcase10.txt
echo testcase11
./a.out testdata/testcase11.txt
echo testcase12
./a.out testdata/testcase12.txt
echo testcase13
./a.out testdata/testcase13.txt
echo testcase14
./a.out testdata/testcase14.txt
echo testcase15
./a.out testdata/testcase15.txt

