echo testcase1
./a.out ../Assn2TestData/testcase1.txt
echo testcase2
./a.out ../Assn2TestData/testcase2.txt
echo testcase3
./a.out ../Assn2TestData/testcase3.txt
echo testcase4
./a.out ../Assn2TestData/testcase4.txt
echo testcase5
./a.out ../Assn2TestData/testcase5.txt
echo testcase6
./a.out ../Assn2TestData/testcase6.txt
echo testcase7
./a.out ../Assn2TestData/testcase7.txt
echo testcase8
./a.out ../Assn2TestData/testcase8.txt
echo testcase9
./a.out ../Assn2TestData/testcase9.txt
echo testcase10
./a.out ../Assn2TestData/testcase10.txt
