echo testcase1
./ans ../assn4-1testdata/testcase1.txt
echo testcase2
./ans ../assn4-1testdata/testcase2.txt
echo testcase3
./ans ../assn4-1testdata/testcase3.txt
echo testcase4
./ans ../assn4-1testdata/testcase4.txt
echo testcase5
./ans ../assn4-1testdata/testcase5.txt
echo testcase6
./ans ../assn4-1testdata/testcase6.txt
echo testcase7
./ans ../assn4-1testdata/testcase7.txt
echo testcase8
./ans ../assn4-1testdata/testcase8.txt
echo testcase9
./ans ../assn4-1testdata/testcase9.txt
echo testcase10
./ans ../assn4-1testdata/testcase10.txt
echo testcase11
./ans ../assn4-1testdata/testcase11.txt
echo testcase12
./ans ../assn4-1testdata/testcase12.txt
