echo testcase1
./merge_sort testcase/assnTestcase1.txt
echo testcase2
./merge_sort testcase/assnTestcase2.txt
echo testcase3
./merge_sort testcase/assnTestcase3.txt
echo testcase4
./merge_sort testcase/assnTestcase4.txt
echo testcase5
./merge_sort testcase/assnTestcase5.txt
echo testcase6
./merge_sort testcase/assnTestcase6.txt
echo testcase7
./merge_sort testcase/assnTestcase7.txt
echo testcase8
./merge_sort testcase/assnTestcase8.txt
echo testcase9
./merge_sort testcase/assnTestcase9.txt
echo testcase10
./merge_sort testcase/assnTestcase10.txt
echo testcase11
./merge_sort testcase/assnTestcase11.txt
echo testcase12
./merge_sort testcase/assnTestcase12.txt
echo testcase13
./merge_sort testcase/assnTestcase13.txt
echo testcase14
./merge_sort testcase/assnTestcase14.txt
echo testcase15
./merge_sort testcase/assnTestcase15.txt
echo testcase16
./merge_sort testcase/assnTestcase16.txt
