echo testcase1
./insertion_sort testcase/assnTestcase1.txt
echo testcase2
./insertion_sort testcase/assnTestcase2.txt
echo testcase3
./insertion_sort testcase/assnTestcase3.txt
echo testcase4
./insertion_sort testcase/assnTestcase4.txt
echo testcase5
./insertion_sort testcase/assnTestcase5.txt
echo testcase6
./insertion_sort testcase/assnTestcase6.txt
echo testcase7
./insertion_sort testcase/assnTestcase7.txt
echo testcase8
./insertion_sort testcase/assnTestcase8.txt
echo testcase9
./insertion_sort testcase/assnTestcase9.txt
echo testcase10
./insertion_sort testcase/assnTestcase10.txt
echo testcase11
./insertion_sort testcase/assnTestcase11.txt
echo testcase12
./insertion_sort testcase/assnTestcase12.txt
echo testcase13
./insertion_sort testcase/assnTestcase13.txt
echo testcase14
./insertion_sort testcase/assnTestcase14.txt
echo testcase15
./insertion_sort testcase/assnTestcase15.txt
echo testcase16
./insertion_sort testcase/assnTestcase16.txt
