echo testcase1
./heap_sort testcase/assnTestcase1.txt
echo testcase2
./heap_sort testcase/assnTestcase2.txt
echo testcase3
./heap_sort testcase/assnTestcase3.txt
echo testcase4
./heap_sort testcase/assnTestcase4.txt
echo testcase5
./heap_sort testcase/assnTestcase5.txt
echo testcase6
./heap_sort testcase/assnTestcase6.txt
echo testcase7
./heap_sort testcase/assnTestcase7.txt
echo testcase8
./heap_sort testcase/assnTestcase8.txt
echo testcase9
./heap_sort testcase/assnTestcase9.txt
echo testcase10
./heap_sort testcase/assnTestcase10.txt
echo testcase11
./heap_sort testcase/assnTestcase11.txt
echo testcase12
./heap_sort testcase/assnTestcase12.txt
echo testcase13
./heap_sort testcase/assnTestcase13.txt
echo testcase14
./heap_sort testcase/assnTestcase14.txt
echo testcase15
./heap_sort testcase/assnTestcase15.txt
echo testcase16
./heap_sort testcase/assnTestcase16.txt
