echo testcase1
./quick_sort testcase/assnTestcase1.txt
echo testcase2
./quick_sort testcase/assnTestcase2.txt
echo testcase3
./quick_sort testcase/assnTestcase3.txt
echo testcase4
./quick_sort testcase/assnTestcase4.txt
echo testcase5
./quick_sort testcase/assnTestcase5.txt
echo testcase6
./quick_sort testcase/assnTestcase6.txt
echo testcase7
./quick_sort testcase/assnTestcase7.txt
echo testcase8
./quick_sort testcase/assnTestcase8.txt
echo testcase9
./quick_sort testcase/assnTestcase9.txt
echo testcase10
./quick_sort testcase/assnTestcase10.txt
echo testcase11
./quick_sort testcase/assnTestcase11.txt
echo testcase12
./quick_sort testcase/assnTestcase12.txt
echo testcase13
./quick_sort testcase/assnTestcase13.txt
echo testcase14
./quick_sort testcase/assnTestcase14.txt
echo testcase15
./quick_sort testcase/assnTestcase15.txt
echo testcase16
./quick_sort testcase/assnTestcase16.txt
