echo testcase1
./a.out ../assn4-2testdata/testcase1.txt
echo testcase2
./a.out ../assn4-2testdata/testcase2.txt
echo testcase3
./a.out ../assn4-2testdata/testcase3.txt
echo testcase4
./a.out ../assn4-2testdata/testcase4.txt
echo testcase5
./a.out ../assn4-2testdata/testcase5.txt
echo testcase6
./a.out ../assn4-2testdata/testcase6.txt
echo testcase7
./a.out ../assn4-2testdata/testcase7.txt
echo testcase8
./a.out ../assn4-2testdata/testcase8.txt
echo testcase9
./a.out ../assn4-2testdata/testcase9.txt
echo testcase10
./a.out ../assn4-2testdata/testcase10.txt
